default:
  cache:  # Cache modules using lock file
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      
# 定义全局变量
variables:
  SSH_HOST: "121.40.145.223"
  # SSH_PORT: "22"
  SSH_USER: "root"
  APP_PATH: "/app/amazing"

stages:
  - build
  - deploy

build:
  stage: build
  image: node:16
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
  - master

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache rsync openssh
  script:
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - rsync -rav --delete dist/ $SSH_USER@$SSH_HOST:$APP_PATH
  only:
    - master