default:
  cache:  # Cache modules using lock file
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      
# 定义全局变量
variables:
  SSH_HOST: "121.40.145.223"
  # SSH_PORT: "22"
  SSH_USER: "root"
  APP_PATH: "/app/amazing/dist/"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
  - master

deploy:
  stage: deploy
  script:
    - scp -r dist/* $SSH_USER@$SSH_HOST:$APP_PATH # 将构建产物拷贝到服务器
  only:
    - master